[project]
name = "com.Internet1235.quiet-time-reminder-plugin"
version = "1.1.5"
description = "A Class Widgets plugin."
authors = [
    {name = "RinLit"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["class-widgets-sdk"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
